$(document).ready(function(){
    $(".text1").click(function(){
      $("#image1").show(1000);
      $(".text1").hide(1000);
    });
    $("#image1").click(function(){
      $(".text1").show(1000);
      $("#image1").hide(1000);
    });
   
  });
  $(document).ready(function(){
    $(".text2").click(function(){
      $("#image2").show(1000);
      $(".text2").hide(1000);
    });
    $("#image2").click(function(){
      $(".text2").show(1000);
      $("#image2").hide(1000);
    });
   
  });
  $(document).ready(function(){
    $(".text3").click(function(){
      $("#image3").show(1000);
      $(".text3").hide(1000);
    });
    $("#image3").click(function(){
      $(".text3").show(1000);
      $("#image3").hide(1000);
    });
   
  });
  $(document).ready(function(){
    $(".text4").click(function(){
      $("#image4").show(1000);
      $(".text4").hide(1000);
    });
    $("#image4").click(function(){
      $(".text4").show(1000);
      $("#image4").hide(1000);
    });
   
  });
  $(document).ready(function(){
    $(".text5").click(function(){
      $("#image5").show(1000);
      $(".text5").hide(1000);
    });
    $("#image5").click(function(){
      $(".text5").show(1000);
      $("#image5").hide(1000);
    });
   
  });
  $(document).ready(function(){
    $(".text6").click(function(){
      $("#image6").show(1000);
      $(".text6").hide(1000);
    });
    $("#image6").click(function(){
      $(".text6").show(1000);
      $("#image6").hide(1000);
    });
   
  });
  $(document).ready(function(){
    $(".text7").click(function(){
      $("#image7").show(1000);
      $(".text7").hide(1000);
    });
    $("#image7").click(function(){
      $(".text7").show(1000);
      $("#image7").hide(1000);
    });
   
  });
  $(document).ready(function(){
    $(".text8").click(function(){
      $("#image8").show(1000);
      $(".text8").hide(1000);
    });
    $("#image8").click(function(){
      $(".text8").show(1000);
      $("#image8").hide(1000);
    });
   
  });
  $(document).ready(function(){
    $(".text9").click(function(){
      $("#image9").show(1000);
      $(".text9").hide(1000);
    });
    $("#image9").click(function(){
      $(".text9").show(1000);
      $("#image9").hide(1000);
    });
   
  });
  $(document).ready(function(){
    $(".text10").click(function(){
      $("#image10").show(1000);
      $(".text10").hide(1000);
    });
    $("#image10").click(function(){
      $(".text10").show(1000);
      $("#image10").hide(1000);
    });
   
  });
  $(document).ready(function(){
    $(".text11").click(function(){
      $("#image11").show(1000);
      $(".text11").hide(1000);
    });
    $("#image11").click(function(){
      $(".text11").show(1000);
      $("#image11").hide(1000);
    });
   
  });
  $(document).ready(function(){
    $(".text12").click(function(){
      $("#image12").show(1000);
      $(".text12").hide(1000);
    });
    $("#image12").click(function(){
      $(".text12").show(1000);
      $("#image12").hide(1000);
    });
   
  });
  $(".culture").click(function(){
    $("#image1").fadeIn(1500);
    $(".culture").fadeOut(1500);
  });
  $("#image1").click(function(){
    $(".culture").fadeIn(1500);
    $("#image1").fadeOut(1500);
  });
 
});
$(document).ready(function(){
  $("#image2").click(function(){
    $("#text2").fadeIn(1500);
    $("#image2").fadeOut(1500);
  });
  $("#text2").click(function(){
    $("#image2").fadeIn(1500);
    $("#text2").fadeOut(1500);
  });
});
$(document).ready(function(){
  $("#image3").click(function(){
    $("#text3").fadeIn(1500);
    $("#image3").fadeOut(1500);
  });
  $("#text3").click(function(){
    $("#image3").fadeIn(1500);
    $("#text3").fadeOut(1500);
  });
});
$(document).ready(function(){
  $("#image4").click(function(){
    $("#text4").fadeIn(1500);
    $("#image4").fadeOut(1500);
  });
  $("#text4").click(function(){
    $("#image4").fadeIn(1500);
    $("#text4").fadeOut(1500);
  });
});
$(document).ready(function(){
  $("#image5").click(function(){
    $("#text5").fadeIn(1500);
    $("#image5").fadeOut(1500);
  });
  $("#text5").click(function(){
    $("#image5").fadeIn(1500);
    $("#text5").fadeOut(1500);
  });
});

