$(document).ready(function(){
  $(".culture").click(function(){
    $("#image1").show(1000);
    $(".culture").hide(1000);
  });
  $("#image1").click(function(){
    $(".culture").show(1000);
    $("#image1").hide(1000);
  });
 
});
$(document).ready(function(){
  $("#image2").click(function(){
    $("#text2").show(1000);
    $("#image2").hide(1000);
  });
  $("#text2").click(function(){
    $("#image2").show(1000);
    $("#text2").hide(1000);
  });
});
$(document).ready(function(){
  $("#image3").click(function(){
    $("#text3").show(1000);
    $("#image3").hide(1000);
  });
  $("#text3").click(function(){
    $("#image3").show(1000);
    $("#text3").hide(1000);
  });
});
$(document).ready(function(){
  $("#image4").click(function(){
    $("#text4").fadeIn(1500);
    $("#image4").fadeOut(1500);
  });
  $("#text4").click(function(){
    $("#image4").fadeIn(1500);
    $("#text4").fadeOut(1500);
  });
});
$(document).ready(function(){
  $("#image5").click(function(){
    $("#text5").fadeIn(1500);
    $("#image5").fadeOut(1500);
  });
  $("#text5").click(function(){
    $("#image5").fadeIn(1500);
    $("#text5").fadeOut(1500);
  });
});
